Notes on IPSEC
==============

* AH versus ESP
+
"Authentication Header" (AH) and "Encapsulating Security Payload" (ESP) are the
two main wire-level protocols used by IPsec, and they authenticate (AH) and
encrypt+authenticate (ESP) the data flowing over that connection. They are
typically used independently, though it's possible (but uncommon) to use them
both together.
+
* Tunnel mode versus Transport mode
+
Transport Mode provides a secure connection between two endpoints as it
encapsulates IP's payload, while Tunnel Mode encapsulates the entire IP packet
to provide a virtual "secure hop" between two gateways. The latter is used to
form a traditional VPN, where the tunnel generally creates a secure tunnel
across an untrusted Internet.
+
* MD5 versus SHA-1 versus DES versus 3DES versus AES versus blah blah blah
+
Setting up an IPsec connection involves all kinds of crypto choices, but this
is simplified substantially by the fact that any given connection can use at
most two or (rarely) three at a time.  Authentication calculates an Integrity
Check Value (ICV) over the packet's contents, and it's usually built on top of
a cryptographic hash such as MD5 or SHA-1. It incorporates a secret key known
to both ends, and this allows the recipient to compute the ICV in the same way.
If the recipient gets the same value, the sender has effectively authenticated
itself (relying on the property that cryptographic hashes can't practically be
reversed). AH always provides authentication, and ESP does so optionally.
Encryption uses a secret key to encrypt the data before transmission, and this
hides the actual contents of the packet from eavesdroppers. There are quite a
few choices for algorithms here, with DES, 3DES, Blowfish and AES being common.
Others are possible too.
+
* IKE versus manual keys
+
Since both sides of the conversation need to know the secret values used in
hashing or encryption, there is the question of just how this data is
exchanged. Manual keys require manual entry of the secret values on both ends,
presumably conveyed by some out-of-band mechanism, and IKE (Internet Key
Exchange) is a sophisticated mechanism for doing this online.
+
* Main mode versus aggressive mode
+
These modes control an efficiency-versus-security tradeoff during initial IKE
key exchange. "Main mode" requires six packets back and forth, but affords
complete security during the establishment of an IPsec connection, while
Aggressive mode uses half the exchanges providing a bit less security because
some information is transmitted in cleartext.
+





Sources
-------

* http://www.unixwiz.net/techtips/iguide-ipsec.html
