Notes from reading Network Warrior
==================================

Diff between Hub and Router
---------------------------

* Hub simply replicates everything on all ports
* Switch learns which port has which mac. This is typically on a CAM.
* Hubs can easily cause loops - making collision detect messy. Switches dont suffer

AutoNegotiation
---------------

* Negotiates both Speed and Duplex mode
* (My thinking:) Too low level stuff, move on


VLAN
----

* Origianl VLAN simply represents grouping physical ports at switches w/o any knowledge to end machines, that still send normal ethernet pkts
* Trunk is a special port which carries pkts from all VLANs from one switch to another. The pkts in this trunk are encapsulated in a ISL protocol header.
* 802.1Q is a newer introduction, where end uses themeselves tag their pkts.


Notes from Routing TCP-IP - Vol I Cisco press
==============================================

Static route
------------

* Simple static routes
** Key componets are ip/mask , next-hop-ip, [ administrative-distance ]
** next hop ip can be an interface for directly reachable sub-nets
* Summary routes
** Collapse masks together
* Alternate route
** Routes needn't be bi-directionally symmetric.
* Floating static routes
** *Administrative distance* is 1 for routes and 0 for direct subnets. Optionally it can be
   configured to a higher number (typically 50). These are floating routes, that serve as
   backup routes.
** Dynamic routes administrative distances are always more than 1, so that static routes have precedence.
   But its not clear of precedence with these floating routes.
** This is pure-backup set, not load-sharing.
* Load sharing
** To acheive load-sharing, each route has another parameter called - *cost*
** Again lower cost -> preferred more.

