Notes from reading Network Warrior
==================================

Diff between Hub and Router
---------------------------

* Hub simply replicates everything on all ports
* Switch learns which port has which mac. This is typically on a CAM.
* Hubs can easily cause loops - making collision detect messy. Switches dont suffer

AutoNegotiation
---------------

* Negotiates both Speed and Duplex mode
* (My thinking:) Too low level stuff, move on


VLAN
----

* Origianl VLAN simply represents grouping physical ports at switches w/o any knowledge to end machines, that still send normal ethernet pkts
* Trunk is a special port which carries pkts from all VLANs from one switch to another. The pkts in this trunk are encapsulated in a ISL protocol header.
* 802.1Q is a newer introduction, where end uses themeselves tag their pkts.


Notes from Routing TCP-IP - Vol I Cisco press
==============================================

Static route
------------

* Simple static routes
** Key componets are ip/mask , next-hop-ip, [ administrative-distance ]
** next hop ip can be an interface for directly reachable sub-nets
* Summary routes
** Collapse masks together
* Alternate route
** Routes needn't be bi-directionally symmetric.
* Floating static routes
** *Administrative distance* is 1 for routes and 0 for direct subnets. Optionally it can be
   configured to a higher number (typically 50). These are floating routes, that serve as
   backup routes.
** Dynamic routes administrative distances are always more than 1, so that static routes have precedence.
   But its not clear of precedence with these floating routes.
** This is pure-backup set, not load-sharing.
** Administrative-distance is telling how the route is learnt (the source of the route). Here are
   some common sources and their administrative-distances.
+
----
SOURCE OF THE ROUTE                               DEFAULT DISTANCE

Connected Interface or static route to an Interface   0
Static route to an IP Address                         1
EIGRP Summary                                         5
BGP External                                          20
EIGRP Internal                                        90
IGRP                                                  100
OSPF                                                  110
IS-IS                                                 115
RIP                                                   120
EIGRP External                                        170
BGP Internal                                          200
Unknown Source                                        255
----
+
* Load sharing
** To acheive load-sharing, each route has a - *cost*. Cost is a generic term to whatever
   metric the routing protocol uses.
** Again lower cost -> preferred more.
** Routing protocols can be either equal cost routing protocols - always choosing the
   best cost route (or) unequal cost routing protocols (can choose routes with every
   cost value proportionally).
** Load sharing is either per-destination or per-pkt. (former is called as fast-switching
   and later is process-switching)

* Recursie lookup
** A next-hop router need not be directly connected. In that case, the router does a
   lookup for the next-hop once again to resolve recursively, until the directly connected
   route is available.
** Naturally, this kills forwarding times. But this gives to normalization of routes, so
   that minimal changes are needed on topology changes.

* TroubleShooting
** Ensure both forward and return paths are good when debugging routing.

Proxy Arp: A router answers to a ARP query of another host. It then collects the traffic and
           forwards it to the host.

Dynamic Routing
---------------

Every dynamic routing protocol should have the following characteristics:
* A procedure for passing reachability information about networks to other routers.
* A procedure for receiving reachability information from other routers
* A procedure for determining optimal routes based on the reachability information it
  has and for recording this information in a route table
* A procedure for reacting to, compensating for, and advertising topology changes
  in an internetwork

Issues common to all routing protocols:
path determination, metrics, convergence, and load balancing.

