SAE and LTE General Understanding
==================================
:toc:

== List of interfaces

* S1   -  Data plane from Enb to SGW
* S2   -
* S2a  -  Trusted non-3GPP to PGW (can be PMIP or TWAG)
* S2b  -  Non-Trusted non-3GPP to PGW (ePDG)
* S3   -  S4-SGSN to MME
* S4   -  S4-SGSN to SGW
* S5   -  SGW to PGW
* S6   -
* S6a  -  MME to HSS
* S6d  -  S4-SGSN to HSS
* S7   -  NOT_DEFINED
* S8   -  inter-plmn S5->S9
* S9   -  home PCRF to visited PCRF
* S10  -  inter MME
* S11  -  MME to SGW
* S12  -  Direct Tunnel RNC->SGW
* S13  -  MME to EIR
* S14  -  NOT_DEFINED
* S15  -  NOT_DEFINED
* S16  -  S4-SGSN to S4-SGSN
* S101
* SGi

Gx -  PCRF to PGW
Gy -  offline charging to PGW
Gz -  online charging to PGW

UMTS

Iu - RNC to SGSN
Gr - SGSN to HLR
Gi - GGSN to IP-Network

== Policy and Bearers

* The PGW and PCRF maintain session-level contexts.
* Each session is identified at PGW by (IMSI,APN-requested,Access-type) and so is it as PCRF
* The following is the hierarchy of information exchanged between PGW and PCRF
** Session-level
*** Default-Bearer's QCI/ARP
*** AMBR for session
** Bunch of Rules. Each rule has the following
*** Match criteria
*** Action.
+
This could be just gating/drop or apply some Qos. Qos is specified in terms of a QCI/ARP. Another action
is to classify this traffic into a (Rating-Grounp,service-id) for charging.
+
* The PCRF and PGW are in sync about the current session that is ongoing, and
  the rules that are applied/in-progress
  for that session.
* The PCRF may at any point add a new rule to a session, delete a rule or edit a rule.
* Note that there is no notion of bearer per se, between PCRF and PGW

=== Understanding a Rule

* Rules have priority amongst them. So Rules with higher priority are evaluated first.
* Within a rule there are multiple match-criteria. These are natually ordered in the order
  in which PCRF specified them.
+
For eg, Say Rule R1 has M1,M2,M3 and Rule R2 has M4,M5  and R1 has highter priority, then a
PGW will apply M1,M2,M3,M4 and M5 in that order


=== PGW job of mapping Rules to Bearers

* PGW basically decides to create a new bearer if any new rule has a different (QCI/ARP) from
  other existing rules. This is because each bearer has a unique (QCI/ARP) for itself.

=== Open Questions?

* Is APN-AMBR really session level?
* Is there a UE-AMBR? Does SGW apply it then?
* Does matches have bit-rates apart from QCI/ARP. How does that work?

